// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://nsivonkznycafnacjteg.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zaXZvbmt6bnljYWZuYWNqdGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzMTY0ODAsImV4cCI6MjA0Nzg5MjQ4MH0.kBm5MHiKYkS6m4ScvaaoQ68N6TT_0HBxUqQll3y-DW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);